CREATE DATABASE DUAN1_NHOM6_PMBANQUANAO
GO
USE DUAN1_NHOM6_PMBANQUANAO
GO

CREATE TABLE SanPham
(
  IdSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaSP VARCHAR(20) UNIQUE,
  TenSP NVARCHAR(50) DEFAULT NULL,
  TinhTrang INT
) 
GO
INSERT INTO SanPham(MaSP,TenSP,TinhTrang)
VALUES('SP01',N'Áo',1)

SELECT * FROM SanPham

CREATE TABLE LoaiSP
(
  IdLoaiSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaLoai VARCHAR(20) UNIQUE,
  TenLoai NVARCHAR(50) DEFAULT NULL,
  TinhTrang INT
) 
GO
INSERT INTO LoaiSP(MaLoai,TenLoai,TinhTrang)
VALUES('L01',N'Polo',1)

SELECT * FROM LoaiSP

CREATE TABLE ChatLieu
(
  IdCL UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaCL VARCHAR(20) UNIQUE,
  TenCL NVARCHAR(50) DEFAULT NULL
) 
GO
INSERT INTO ChatLieu(MaCL,TenCL)
VALUES('CL01',N'Cotton')

SELECT * FROM ChatLieu

CREATE TABLE Size
(
  IdSize UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaSize VARCHAR(20) UNIQUE,
  TenSize NVARCHAR(50) DEFAULT NULL
) 
GO
INSERT INTO Size(MaSize,TenSize)
VALUES('SZ01',N'Size 2XL')

SELECT * FROM Size

CREATE TABLE MauSac
(
  IdMau UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaMau VARCHAR(20) UNIQUE,
  TenMau NVARCHAR(50) DEFAULT NULL
) 
GO
INSERT INTO MauSac(MaMau,TenMau)
VALUES('M01',N'PINK')

SELECT * FROM MauSac

CREATE TABLE ChiTietSP
(
  IdCTSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  IdSP UNIQUEIDENTIFIER,
  IdLoaiSP UNIQUEIDENTIFIER,
  IdCL UNIQUEIDENTIFIER,
  IdSize UNIQUEIDENTIFIER,
  IdMau UNIQUEIDENTIFIER,
  SoLuongTon INT,
  Gia DECIMAL(20,0) DEFAULT 0,
  MoTa NVARCHAR(100) DEFAULT NULL,
  TinhTrang INT,
  NgayTao DATE DEFAULT NULL,
  NgaySua DATE DEFAULT NULL,
  FOREIGN KEY (IdSP) REFERENCES SanPham(IdSP),
  FOREIGN KEY (IdLoaiSP) REFERENCES LoaiSP(IdLoaiSP),
  FOREIGN KEY (IdCL) REFERENCES ChatLieu(IdCL),
  FOREIGN KEY (IdSize) REFERENCES Size(IdSize),
  FOREIGN KEY (IdMau) REFERENCES MauSac(IdMau)
)
GO

INSERT INTO ChiTietSP(IdSP, IdLoaiSP, IdCL, IdSize, IdMau, SoLuongTon, Gia, MoTa, TinhTrang, NgayTao, NgaySua)
VALUES('E1ED7368-99EF-4519-8AA1-3AC8CD76110C','4D536332-C395-4972-8298-B4180B96E6EE','EC285128-13B8-4639-8EE2-C5894354B3B9','D72FC67F-E7D3-4473-90F8-0F234272E693',
'71F3BA5B-09A6-4B7D-B854-780E72216D33', 20, 150000, N'ĐỐT KHÔNG CHÁY, CẮT KHÔNG RÁCH, SÚNG BẮN KHÔNG THỦNG', 1, '10-11-2022','11-11-2022')

SELECT*FROM ChiTietSP

CREATE TABLE ChucVu
(
  IdCV UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaCV VARCHAR(20) UNIQUE,
  TenCV NVARCHAR(50) DEFAULT NULL
) 
GO

INSERT INTO ChucVu(MaCV,TenCV)
VALUES('CV01',N'Nhân Viên')

SELECT * FROM ChucVu

CREATE TABLE NguoiDung
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdCV UNIQUEIDENTIFIER,
	MaND VARCHAR(20) UNIQUE,
	TenTK NVARCHAR(30),
	MatKhau VARCHAR(MAX) DEFAULT NULL,
	HoVaTen NVARCHAR(100) DEFAULT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	Email NVARCHAR(50) DEFAULT NULL,
	Sdt VARCHAR(10) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	[CCCD/CMT] NVARCHAR(12) DEFAULT NULL,
	TinhTrang INT,
	NgayTao DATE DEFAULT NULL,
	NgaySua DATE DEFAULT NULL,
	FOREIGN KEY (IdCV) REFERENCES ChucVu(IdCV),
)
GO

INSERT INTO NguoiDung(IdCV,MaND,TenTK,MatKhau, HoVaTen, GioiTinh, NgaySinh, Email, Sdt, DiaChi, [CCCD/CMT], TinhTrang, NgayTao, NgaySua)
VALUES('FC9BB7FF-A8B7-400A-AFDA-75D1A56126B6',N'ND01','vanne1312',13121112,N'Lê Thị Nguyệt Vân',N'Nữ',
'1-12-2003','vanltnph26342@fpt.edu.vn','0932343783',N'Hoá Chất','001304656874',1,'10-11-2022','11-11-2022')

SELECT*FROM NguoiDung

CREATE TABLE KhachHang
(
	IdKH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKH VARCHAR(20) UNIQUE,
	HoVaTen NVARCHAR(100) DEFAULT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	Sdt VARCHAR(10) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	NgayTao DATE DEFAULT NULL,
	NgaySua DATE DEFAULT NULL,
)
GO

INSERT INTO KhachHang(MaKH, HoVaTen, GioiTinh, DiaChi, Sdt, NgaySinh, NgayTao, NgaySua)
VALUES ('KH01',N'Nguyễn Thị Mai',N'Nữ',N'Thất Thanh','0866127018','03-12-2003','10-11-2022','11-11-2022')

SELECT * FROM KhachHang

CREATE TABLE HoaDon
(
	IdHD UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdND UNIQUEIDENTIFIER,
	IdKH UNIQUEIDENTIFIER,
	MaHD VARCHAR(20) UNIQUE,
	PhuongThucTT INT,
	TongTien DECIMAL(20,0) DEFAULT 0,
	TinhTrang INT,
	NgayTao DATE DEFAULT NULL,
	NgaySua DATE DEFAULT NULL,
	FOREIGN KEY (IdND) REFERENCES NguoiDung(Id),
	FOREIGN KEY (IdKH) REFERENCES KhachHang(IdKH),

)
GO

INSERT INTO HoaDon(IdND, IdKH, MaHD, PhuongThucTT, TongTien, TinhTrang, NgayTao, NgaySua)
VALUES('D815C5FD-53A2-4589-A165-AEB81890A8AB','327CD523-1D69-43B1-BC0A-7493037056F5','HD01',1,250000,1,'10-11-2022','11-11-2022')

SELECT * FROM HoaDon

CREATE TABLE KhuyenMai
(
	IdKM UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKM VARCHAR(20) UNIQUE,
	TenKM NVARCHAR(50),
	NgayBatDau DATE DEFAULT NULL,
	NgayKetThuc DATE DEFAULT NULL,
	MoTa NVARCHAR(50) DEFAULT NULL,
	GiamGia INT,
	TinhTrang INT,
	NgayTao DATE DEFAULT NULL,
	NgaySua DATE DEFAULT NULL,

)
GO

INSERT INTO KhuyenMai(MaKM, TenKM, NgayBatDau, NgayKetThuc, MoTa, GiamGia, TinhTrang, NgayTao, NgaySua)
VALUES('KM01','SALE 20-11','2022-11-19','2022-11-20', N'Tất cả sản phẩm đã rách sale 99%',99,1,'10-11-2022','11-11-2022')

SELECT * FROM KhuyenMai

CREATE TABLE HoaDonCT
(
	IdHDCT UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdHD UNIQUEIDENTIFIER,
	IdKM UNIQUEIDENTIFIER,
	IdCTSP UNIQUEIDENTIFIER,
	Gia DECIMAL(20,0) DEFAULT 0,
	SoLuongMua INT,
	GiaKM DECIMAL(20,0) DEFAULT 0,
	FOREIGN KEY (IdHD) REFERENCES HoaDon(IdHD),
	FOREIGN KEY (IdCTSP) REFERENCES ChiTietSP(IdCTSP),
	FOREIGN KEY (IdKM) REFERENCES KhuyenMai(IdKM),

)
GO
INSERT INTO HoaDonCT(IdHD,IdKM,IdCTSP,Gia,SoLuongMua,GiaKM)
VALUES('56B8DC09-5299-40F1-8A0A-78A2A7BDA668','2EFD1EBA-B284-44B7-87B7-E74B6031774C', 'A0F3B523-E74B-47F3-8E32-5E6AAC858C6E', 150000 ,1,150000)

SELECT * FROM HoaDonCT

CREATE TABLE Anh
(
  IdAnh UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  IDCTSP UNIQUEIDENTIFIER,
  MaAnh VARCHAR(20) UNIQUE,
  TenAnh NVARCHAR(50) DEFAULT NULL,
  DuongDanAnh NVARCHAR(100) DEFAULT NULL,
  FOREIGN KEY (IDCTSP) REFERENCES ChiTietSP(IDCTSP),
) 
GO
INSERT INTO Anh(IDCTSP, MaAnh, TenAnh, DuongDanAnh)
VALUES('A0F3B523-E74B-47F3-8E32-5E6AAC858C6E','A01',N'ẢNH Áo POLO',NULL)

SELECT * FROM Anh

CREATE TABLE DoiTra
(
  IdDoiTra UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  IDHD UNIQUEIDENTIFIER,
  LyDoDoiTra NVARCHAR(200) UNIQUE,
  NgayDoiTra DATE DEFAULT NULL, 
  HanDoiTra DATE DEFAULT NULL, 
  FOREIGN KEY (IDHD) REFERENCES HoaDon(IDHD),
) 
GO

INSERT INTO DoiTra(IDHD, LyDoDoiTra, NgayDoiTra, HanDoiTra)
VALUES('56B8DC09-5299-40F1-8A0A-78A2A7BDA668',N'Sản phẩm khác với mô tả: Đốt vẫn cháy','2022-11-13','2022-11-15')

SELECT * FROM DoiTra