CREATE DATABASE DUAN1_NHOM6_PMBANQUANAO
GO
USE DUAN1_NHOM6_PMBANQUANAO
GO

CREATE TABLE SanPham
(
  IdSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaSP VARCHAR(20) UNIQUE,
  TenSP NVARCHAR(50) DEFAULT NULL,
  TinhTrang INT
) 
GO
INSERT INTO SanPham(MaSP,TenSP,TinhTrang)
VALUES('SP01',N'Áo',1)

SELECT * FROM SanPham

CREATE TABLE LoaiSP
(
  IdLoaiSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaLoai VARCHAR(20) UNIQUE,
  TenLoai NVARCHAR(50) DEFAULT NULL,
  TinhTrang INT
) 
GO
INSERT INTO LoaiSP(MaLoai,TenLoai,TinhTrang)
VALUES('L01',N'Polo',1)

SELECT * FROM LoaiSP

CREATE TABLE ChatLieu
(
  IdCL UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaCL VARCHAR(20) UNIQUE,
  TenCL NVARCHAR(50) DEFAULT NULL
) 
GO
INSERT INTO ChatLieu(MaCL,TenCL)
VALUES('CL01',N'Cotton')

SELECT * FROM ChatLieu

CREATE TABLE Size
(
  IdSize UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaSize VARCHAR(20) UNIQUE,
  TenSize NVARCHAR(50) DEFAULT NULL
) 
GO
INSERT INTO Size(MaSize,TenSize)
VALUES('SZ01',N'Size 2XL')

SELECT * FROM Size

CREATE TABLE MauSac
(
  IdMau UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaMau VARCHAR(20) UNIQUE,
  TenMau NVARCHAR(50) DEFAULT NULL
) 
GO
INSERT INTO MauSac(MaMau,TenMau)
VALUES('M01',N'PINK')

SELECT * FROM MauSac

CREATE TABLE ChiTietSP
(
  IdCTSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  IdSP UNIQUEIDENTIFIER,
  IdLoaiSP UNIQUEIDENTIFIER,
  IdCL UNIQUEIDENTIFIER,
  IdSize UNIQUEIDENTIFIER,
  IdMau UNIQUEIDENTIFIER,
  SoLuongTon INT,
  Gia DECIMAL(20,0) DEFAULT 0,
  MoTa NVARCHAR(100) DEFAULT NULL,
  TinhTrang INT,
  NgayTao DATE DEFAULT NULL,
  NgaySua DATE DEFAULT NULL,
  FOREIGN KEY (IdSP) REFERENCES SanPham(IdSP),
  FOREIGN KEY (IdLoaiSP) REFERENCES LoaiSP(IdLoaiSP),
  FOREIGN KEY (IdCL) REFERENCES ChatLieu(IdCL),
  FOREIGN KEY (IdSize) REFERENCES Size(IdSize),
  FOREIGN KEY (IdMau) REFERENCES MauSac(IdMau)
)
GO

INSERT INTO ChiTietSP(IdSP, IdLoaiSP, IdCL, IdSize, IdMau, SoLuongTon, Gia, MoTa, TinhTrang, NgayTao, NgaySua)
VALUES('EB28071D-00CF-44C3-8AA8-A42EC88BE931','F65EB17C-DD69-4D2D-9786-90740E7C4E9E','2BDD60A9-670D-4478-ABF6-B9217A226BBD','8617D126-945E-430E-9D90-A65EE66A7688',
'90551E51-1F14-41F1-BCB1-84001BB8942C', 20, 150000, N'ĐỐT KHÔNG CHÁY, CẮT KHÔNG RÁCH, SÚNG BẮN KHÔNG THỦNG', 1, '10-11-2022','11-11-2022')
SELECT * FROM SanPham
SELECT * FROM LoaiSP
SELECT * FROM ChatLieu
SELECT * FROM Size
SELECT * FROM MauSac
SELECT*FROM ChiTietSP

CREATE TABLE ChucVu
(
  IdCV UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  MaCV VARCHAR(20) UNIQUE,
  TenCV NVARCHAR(50) DEFAULT NULL
) 
GO

INSERT INTO ChucVu(MaCV,TenCV)
VALUES('CV01',N'Nhân Viên')
INSERT INTO ChucVu(MaCV,TenCV)
VALUES('CV00',N'Quản lý')

SELECT * FROM ChucVu

CREATE TABLE NguoiDung
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdCV UNIQUEIDENTIFIER,
	MaND VARCHAR(20) UNIQUE,
	TenTK NVARCHAR(30),
	MatKhau VARCHAR(MAX) DEFAULT NULL,
	HoVaTen NVARCHAR(100) DEFAULT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	Email NVARCHAR(50) DEFAULT NULL,
	Sdt VARCHAR(10) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	[CCCD/CMT] NVARCHAR(12) DEFAULT NULL,
	TinhTrang INT,
	NgayTao DATE DEFAULT NULL,
	NgaySua DATE DEFAULT NULL,
	FOREIGN KEY (IdCV) REFERENCES ChucVu(IdCV),
)
GO
select * from ChucVu
INSERT INTO NguoiDung(IdCV,MaND,TenTK,MatKhau, HoVaTen, GioiTinh, NgaySinh, Email, Sdt, DiaChi, [CCCD/CMT], TinhTrang, NgayTao, NgaySua)
VALUES('C7434AFC-4C68-40CC-9295-C353063AA54D',N'ND01','nv1',123,N'Lê Thị Nguyệt Mai',N'Nữ',
'1-12-2003','danhpnph26382@fpt.edu.vn','0932343783',N'Hồ Tùng Mậu','001304656874',1,'10-11-2022','11-11-2022')
INSERT INTO NguoiDung(IdCV,MaND,TenTK,MatKhau, HoVaTen, GioiTinh, NgaySinh, Email, Sdt, DiaChi, [CCCD/CMT], TinhTrang, NgayTao, NgaySua)
VALUES('4BFA0510-0337-4728-BAD0-CB8FB40231FD',N'ADMIN','admin',123,N'Phan Ngọc Danh',N'Nam',
'1-12-2003','danhpnph26382@fpt.edu.vn','0932343783',N'Nam Đinh city','001304656874',1,'10-11-2022','11-11-2022')
SELECT*FROM NguoiDung

CREATE TABLE KhachHang
(
	IdKH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKH VARCHAR(20) UNIQUE,
	HoVaTen NVARCHAR(100) DEFAULT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	Sdt VARCHAR(10) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	NgayTao DATE DEFAULT NULL,
	NgaySua DATE DEFAULT NULL,
)
GO
INSERT INTO KhachHang(MaKH, HoVaTen, GioiTinh, DiaChi, Sdt, NgaySinh, NgayTao, NgaySua)
VALUES ('KH00',N'NKhách bán lẻ',N'null',N'null','null','03-12-2003','10-11-2022','11-11-2022')
INSERT INTO KhachHang(MaKH, HoVaTen, GioiTinh, DiaChi, Sdt, NgaySinh, NgayTao, NgaySua)
VALUES ('KH01',N'Ngô Phạm Công',N'Nam',N'Hà Nội','0866127018','03-12-2003','10-11-2022','11-11-2022')

SELECT * FROM KhachHang

CREATE TABLE HoaDon
(
	IdHD UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdND UNIQUEIDENTIFIER,
	IdKH UNIQUEIDENTIFIER,
	MaHD VARCHAR(20) UNIQUE,
	PhuongThucTT INT,
	TongTienMat DECIMAL(20,0) DEFAULT 0,
	TongTienCk DECIMAL(20,0) DEFAULT 0,
	TinhTrang INT,
	NgayTao DATE DEFAULT NULL,
	NgayThanhToan DATE DEFAULT NULL,
	TTTT INT,
	NgayMuonNhan DATE DEFAULT NULL,
	NgayGui DATE DEFAULT NULL,
	NgayNhan DATE DEFAULT NULL,
	TienShip DECIMAL(20,0) DEFAULT 0,
	TenNguoiShip VARCHAR(50),
	SDTNguoiShip VARCHAR(20),
	FOREIGN KEY (IdND) REFERENCES NguoiDung(Id),
	FOREIGN KEY (IdKH) REFERENCES KhachHang(IdKH),
)
GO
SELECT * FROM HoaDon

CREATE TABLE KhuyenMai
(
	IdKM UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKM VARCHAR(20) UNIQUE,
	TenKM NVARCHAR(50),
	NgayBatDau DATE DEFAULT NULL,
	NgayKetThuc DATE DEFAULT NULL,
	MoTa NVARCHAR(50) DEFAULT NULL,
	GiamGia INT,
	TinhTrang INT,
	NgayTao DATE DEFAULT NULL,
	NgaySua DATE DEFAULT NULL,

)
GO

INSERT INTO KhuyenMai(MaKM, TenKM, NgayBatDau, NgayKetThuc, MoTa, GiamGia, TinhTrang, NgayTao, NgaySua)
VALUES('KM01','SALE 20-11','2022-11-19','2022-11-20', N'Không Sale',0,1,'10-11-2022','11-11-2022')
SELECT * FROM KhuyenMai

CREATE TABLE HoaDonCT
(
	IdHDCT UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdHD UNIQUEIDENTIFIER,
	IdKM UNIQUEIDENTIFIER,
	IdCTSP UNIQUEIDENTIFIER,
	Gia DECIMAL(20,0) DEFAULT 0,
	SoLuongMua INT,
	GiaKM DECIMAL(20,0) DEFAULT 0,
	FOREIGN KEY (IdHD) REFERENCES HoaDon(IdHD),
	FOREIGN KEY (IdCTSP) REFERENCES ChiTietSP(IdCTSP),
	FOREIGN KEY (IdKM) REFERENCES KhuyenMai(IdKM),

)
GO

SELECT * FROM HoaDonCT



